image: mcr.microsoft.com/dotnet/sdk:8.0
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:          
  - test

nunit:
    stage: test
    script:
        - dotnet test
