image: mcr.microsoft.com/dotnet/aspnet:8.0
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:          
  - test

nunit:
    stage: test
    script:
        - dotnet test
