stages:          
  - test
  - build

nunit:
  services:
    - name: docker:dind
      command: [ "--tls=false" ]

  variables:
    # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
      - dotnet test
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-image:
  stage: build
  image: docker:20.10.10
  services:
        - docker:20.10.10-dind
  rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_TAG
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG