INSERT INTO "Clients" ("BuyerName", "BuyerAddress", "BuyerCode", "VatCode") VALUES 
                                                                      ('NameOaa', 'Test adreess', '111aa', '157890'),
                                                                      ('asxzx', 'where', '111441a', null),
                                                                      ('aaaa222', 'planet eeee2', '999945410', '44'),
                                                                      ('xt6578iu', 'invisible', '451', '99'),
                                                                      ('My Name Is What?', 'em wha', '377', '8766'),
                                                                      ('The 2 time indeed', 'back to back', '1411', '1478'),
                                                                      ('Au/ra', 'de', '588', '250'),
                                                                      ('xala', 'void?', '511', '052'),
                                                                      ('Fiscit', 'earth', '743', '88'),
                                                                      ('no dollar sign', 'no $', '888', '931'),
                                                                      ('Kentaro', 'animated world', '99741', '5412'),
                                                                      ('How Is this even ', 'ghost', '1243', '87545'),
                                                                      ('Gonna work lmaaaa', 'works for me', '4332', '6321'),
                                                                      ('Yenne', 'Kaer Mooo', '97620', '88'),
                                                                      ('Triss', 'Velen', '557', '65654'),
                                                                      ('Panam', 'Night city', '321789', '443'),
                                                                      ('Going to the moon for sure', 'Rocketttt', '541', '3320'),
                                                                      ('Nitzsche?', 'germ?', '9641', '48'),
                                                                      ('FFFire guy', 'lava world', '8754', '351'),
                                                                      ('ME:)', 'earth', '3278', '779');